### ISSUE TITLE
Include facebook feed widget

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-sublime-time#43]
Similar to how we embedded the facebook page iframe widget for pumpkinsfresno.com, please code in the same iframe in her "News" section below the 3 videos. Give the iframe the max width (i think it's 500px) and make it centered. 

https://developers.facebook.com/docs/plugins/page-plugin

due:
1-5-16  4p

**Comment by jarantfos** [comment]
This isn't working out well for me haha, I've tried embedding the facebook page element, including the JS code, and it's not functional, it just shows the name of the page. I cloned the pumpkin page and checked it out, and that wasn't working locally either, even though it's working fine on the gh-pages. I checked out the console, and it says 
"file://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.4 Failed to load resource: net::ERR_FILE_NOT_FOUND" 
which seems like it could be problematic. This is confusing me though because like I said, I cloned this directly from github and it's functioning on the gh-pages. I tried removing the 'file://' from the line in the JavaScript included for Facebook, and that stops the error message from occurring, but the display is still not functional. I'm really confused here so any help at all would be appreciated - thanks!

**Comment by rodneystrong** [comment]
Hmm.. I just checked this out and it seems to be working just fine. http://editllc.github.io/client-sublime-time/

Please FTP this when you get a chance.

**Comment by jarantfos** [comment]
That's weird. it just doesn't seem to be working locally for me then. I'll
FTP it right now
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by rodneystrong** [comment]
I can actually explain.. It's BECAUSE you were testing it locally. These widgets only work when they are being served over http/https (a webserver). I imagine it would work if you tested on a local WAMP setup. 

This is part of the reason why we use gh-pages as a staging option before we go live because their environment is more identical to the live setup than the local environment is. 

The philosophy behind that is to attempt to minimize the number of variables that can go wrong; one way of doing that is replicating the successful environment as closely as possible. 

Ideally in software development, there are four stages/environments a developer creates/uses a product in: 

Development
Testing
Staging
Production

The names should be self-explanatory in what they represent, but just in case:
Development - When you're initially creating and changing your code heavily
Testing - Stage where a lot of testing/breaking occurs (think of alpha/beta testing)
Staging - The final pre-production environment before the code is deployed
Production - The final environment where the code is pushed for its intended use

I'd be happy to explain this further in person with regards to our setup.

For a deeper explanation/understanding: https://en.wikipedia.org/wiki/Deployment_environment
